/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    FilterBloc: typeof import('./src/components/FilterBloc.vue')['default']
    KpiBloc: typeof import('./src/components/KpiBloc.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowMetric: typeof import('./src/components/ShowMetric.vue')['default']
    ShowMetrics: typeof import('./src/components/ShowMetrics.vue')['default']
  }
}
